spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/notification_db
  rabbitmq:
    host: rabbitmq
  jpa:
    show-sql: false

careflow:
  patient-service:
    base-url: http://patient-service:8082
