apiVersion: v1
kind: Service
metadata:
  name: followup-service
  labels:
    app.kubernetes.io/name: followup-service
    app.kubernetes.io/part-of: careflow-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: followup-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
