server:
  port: 8083

spring:
  application:
    name: clinic-service

  datasource:
    url: jdbc:postgresql://localhost:5435/clinic_db
    username: careflow
    password: careflow

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

careflow:
  internal:
    api-key: careflow-internal-dev-key
