apiVersion: v1
kind: Service
metadata:
  name: clinic-service
  labels:
    app.kubernetes.io/name: clinic-service
    app.kubernetes.io/part-of: careflow-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: clinic-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
