version: '3.9'

services:

  postgres-auth:
    image: postgres:16
    container_name: postgres-auth
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: careflow
      POSTGRES_PASSWORD: careflow
    ports:
      - "5433:5432"

  postgres-patient:
    image: postgres:16
    container_name: postgres-patient
    environment:
      POSTGRES_DB: patient_db
      POSTGRES_USER: careflow
      POSTGRES_PASSWORD: careflow
    ports:
      - "5434:5432"

  postgres-clinic:
    image: postgres:16
    container_name: postgres-clinic
    environment:
      POSTGRES_DB: clinic_db
      POSTGRES_USER: careflow
      POSTGRES_PASSWORD: careflow
    ports:
      - "5435:5432"

  postgres-followup:
    image: postgres:16
    container_name: postgres-followup
    environment:
      POSTGRES_DB: followup_db
      POSTGRES_USER: careflow
      POSTGRES_PASSWORD: careflow
    ports:
      - "5436:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"