apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: careflow-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: notification-service
  ports:
    - name: http
      port: 8085
      targetPort: 8085
