server:
  port: 8080

careflow:
  jwt:
    secret: ${CAREFLOW_JWT_SECRET:careflow-secret-key-careflow-secret-key}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=1
            - id: patient-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1
            - id: clinic-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/clinics/**
              filters:
                - StripPrefix=1
            - id: followup-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/followups/**
              filters:
                - StripPrefix=1
            - id: notification-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/notifications/**
              filters:
                - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: INFO