apiVersion: v1
kind: Service
metadata:
  name: patient-service
  labels:
    app.kubernetes.io/name: patient-service
    app.kubernetes.io/part-of: careflow-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: patient-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
